Run all tests:
    when: manual
    image: vladshambaryan/git_lab_play
    artifacts:
        when: always
        expire_in: 10 days
        paths:
            - allure-report
    before_script:
        - pip install -r requirements.txt
        - playwright install  
    script:
        - pytest --alluredir=allure-results
    after_script:
        - allure generate -c allure-results -o allure-report
        - echo "Report path:https://vladshambaryan.gitlab.io/-/Shop/-/jobs/${CI_JOB_ID}/artifacts/allure-report/index.html" 


Run smoke tests:
    when: manual
    image: vladshambaryan/git_lab_play
    artifacts:
        when: always
        expire_in: 10 days 
        paths:
            - allure-report
    before_script:
        - pip install -r requirements.txt
        - playwright install
    script:
        - pytest -m smoke --alluredir=allure-results
    after_script:
        - allure generate -c allure-results -o allure-report 
        - echo "Report path:https://vladshambaryan.gitlab.io/-/Shop/-/jobs/${CI_JOB_ID}/artifacts/allure-report/index.html"  


Run regression tests:
    when: manual
    image: vladshambaryan/git_lab_play
    artifacts:
        when: always
        expire_in: 10 days
        paths:
            - allure-report
    before_script:
        - pip install -r requirements.txt
        - playwright install
    script:
        - pytest -m regression --alluredir=allure-results
    after_script:
        - allure generate -c allure-results -o allure-report 
        - echo "Report path:https://vladshambaryan.gitlab.io/-/Shop/-/jobs/${CI_JOB_ID}/artifacts/allure-report/index.html"  


Run extended tests:
    when: manual
    image: vladshambaryan/git_lab_play
    artifacts:
        when: always
        expire_in: 10 days
        paths:
            - allure-report
    before_script:
        - pip install -r requirements.txt
        - playwright install
    script:
        - pytest -m extended --alluredir=allure-results
    after_script:
        - allure generate -c allure-results -o allure-report 
        - echo "Report path:https://vladshambaryan.gitlab.io/-/Shop/-/jobs/${CI_JOB_ID}/artifacts/allure-report/index.html"  




# Run all tests:
#     when: manual
#     image: python:3.9
#     artifacts:
#         when: always
#         expire_in: 10 days
#         paths:
#             - allure-report
#     before_script:
#         - pip install -r requirements.txt
#         - apt update && apt install -y openjdk-17-jdk openjdk-17-jre
#         - playwright install
#         - playwright install-deps
#         - wget https://github.com/allure-framework/allure2/releases/download/2.30.0/allure-2.30.0.tgz && tar -zxvf allure-2.30.0.tgz -C /opt/ && ln -s /opt/allure-2.30.0/bin/allure /usr/bin/allure
#     script:
#         - pytest --alluredir=allure-results
#     after_script:
#         - allure generate -c allure-results -o allure-report
#         - echo "Report path:https://vladshambaryan.gitlab.io/-/Test_Ui_Playwright/-/jobs/${CI_JOB_ID}/artifacts/allure-report/index.html"

